  I = imread('cell.tif');
figure, imshow(I), title('imagen original');
[~, threshold] = edge(I, 'sobel');
fudgeFactor = .5;
BWs = edge(I,'sobel', threshold * fudgeFactor);
figure, imshow(BWs), title('Imagen con bordes detectados');
se90 = strel('line', 3, 90);
se0 = strel('line', 3, 0);
BWsdil = imdilate(BWs, [se90 se0]);
figure, imshow(BWsdil), title('Imagen dilatada');
BWdfill = imfill(BWsdil, 'holes');
figure, imshow(BWdfill);
title('imagen con huecos rellenados');
BWnobord = imclearborder(BWdfill, 4);
figure, imshow(BWnobord), title('limpia regiones colindantes con bordes de la imagen');
seD = strel('diamond',1);
BWfinal = imerode(BWnobord,seD);
BWfinal = imerode(BWfinal,seD);
figure, imshow(BWfinal), title('imagen segmentada');